name: Lint
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  Check:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Setup Biome CLI
        uses: biomejs/setup-biome@v2

      - name: Run Biome
        run: biome ci --error-on-warnings --formatter-enabled=false --assist-enabled=false --enforce-assist=false .

